//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int id { get; set; }
        public Nullable<int> idRole { get; set; }
        public string userName { get; set; }
        public string email { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string numberPhone { get; set; }
        public int seriaPass { get; set; }
        public int numberPass { get; set; }
        public Nullable<System.DateTime> birthdayDate { get; set; }
        public string lastInvite { get; set; }
        public Nullable<int> idGender { get; set; }
        public Nullable<int> idTypeInsert { get; set; }
    
        public virtual GenderUser GenderUser { get; set; }
        public virtual RoleUser RoleUser { get; set; }
        public virtual TypeInsert TypeInsert { get; set; }
    }
}
